// <auto-generated />
using System;
using CoreNode.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreNode.Infrastructure.Migrations
{
    [DbContext(typeof(CoreNodeDbContext))]
    partial class CoreNodeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreNode.Domain.Entities.ProxmoxTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Upid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VirtualMachineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualMachineId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.VirtualMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipv4Address")
                        .HasColumnType("text");

                    b.Property<int>("MemoryMB")
                        .HasColumnType("integer");

                    b.Property<int?>("ProxmoxVmId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.ProxmoxTask", b =>
                {
                    b.HasOne("CoreNode.Domain.Entities.VirtualMachine", "VirtualMachine")
                        .WithMany("ProxmoxTask")
                        .HasForeignKey("VirtualMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualMachine");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.VirtualMachine", b =>
                {
                    b.HasOne("CoreNode.Domain.Entities.Tenant", "Tenant")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("VirtualMachines");
                });

            modelBuilder.Entity("CoreNode.Domain.Entities.VirtualMachine", b =>
                {
                    b.Navigation("ProxmoxTask");
                });
#pragma warning restore 612, 618
        }
    }
}
